default:
  s3:
  - label: alberto incoming
    bucket: alberto-input
    path: INCOMING
  - label: alberto outgoing
    bucket: alberto-input
    path: OUTGOING
  - label: sftp-simulator
    bucket: formazione-sftp-simulator
    path: ''
