default:
  s3:
  - label: applicazioni
    bucket: formazione-cherry-applicazione
    path: ''
  - label: formazione
    bucket: formazione-alberto
    path: ''
  - label: sftp-simulator
    bucket: formazione-sftp-simulator
    path: ''
